services:
    project-nginx:
        build:
            context: ./.docker/development
            dockerfile: nginx.docker
        container_name: project-nginx
        volumes:
            - "$PWD/app:/var/www/app:rw"
        depends_on:
            - project-php-fpm
        networks:
            - project-network
        ports:
            - "8082:80"
    project-php-fpm:
        build:
            context: ./.docker/development
            dockerfile: php-fpm.docker
        container_name: project-php-fpm
        volumes:
            - "$PWD/app:/var/www/app:rw"
        environment:
            XDEBUG_CONFIG: "remote_host=192.168.222.1 remote_enable=1"
            PHP_IDE_CONFIG: "serverName=project"
        networks:
            - project-network
networks:
    project-network:
        external: true
